apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
  namespace: backend
  labels:
    deploy: poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registryhbr8656.azurecr.io/tripinsights/poi:latest           
        ports:
        - containerPort: 8080
        env:
        - name: WEB_SERVER_BASE_URI
          value: "http://0.0.0.0"
        - name: WEB_PORT
          value: "8080"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: CONFIG_FILES_PATH
          value: "/secrets"
        volumeMounts:
          - name: secrets-store-inline
            mountPath: "/secrets"
            readOnly: true
      volumes:
      - name: secrets-store-inline
        csi: 
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "trip-insights-vault"
---
apiVersion: v1
kind: Service
metadata:
  name: poi
  namespace: backend
spec:
  type: ClusterIP
  selector:
    app: poi
  ports:
    - protocol: TCP
      name: poi-http
      port: 80
      targetPort: 8080
    - protocol: TCP
      name: poi-https
      port: 443
      targetPort: 443