apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
  namespace: backend
  labels:
    deploy: poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registryhbr8656.azurecr.io/tripinsights/poi:latest
        envFrom:
          - secretRef: 
              name: sql-secrets              
        ports:
        - containerPort: 8080
        env:
        - name: WEB_SERVER_BASE_URI
          value: http:/0.0.0.0
        - name: WEB_PORT
          value: "8080"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
---
apiVersion: v1
kind: Service
metadata:
  name: poi
  namespace: backend
spec:
  type: ClusterIP
  selector:
    app: poi
  ports:
    - protocol: TCP
      name: poi-http
      port: 80
      targetPort: 8080
    - protocol: TCP
      name: poi-https
      port: 443
      targetPort: 443