apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: trip-insights-vault
  namespace: backend
spec:
  provider: azure
  parameters:
    keyvaultName: "trip-insights-vault"       # The name of the Azure Key Vault         
    useVMManagedIdentity: "true"         
    userAssignedIdentityID: "0b455a44-81e4-4ebe-82cf-6b6aa495c2cc"
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, Azure environment will default to AzurePublicCloud 
    objects:  |
      array:
        - |
          objectName: SQL-USER       # In this example, 'ExampleSecret'   
          objectAlias: SQL_USER
          objectType: secret              # Object types: secret, key or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: SQL-PASSWORD       # In this example, 'ExampleSecret'   
          objectAlias: SQL_PASSWORD
          objectType: secret              # Object types: secret, key or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: SQL-SERVER       # In this example, 'ExampleSecret'   
          objectAlias: SQL_SERVER
          objectType: secret              # Object types: secret, key or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: SQL-DBNAME       # In this example, 'ExampleSecret'   
          objectAlias: SQL_DBNAME
          objectType: secret              # Object types: secret, key or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty                              
    tenantId: "89093f41-f2fc-4852-822c-84a94b26a9be"               # the tenant ID containing the Azure Key Vault instance