apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-deployment
  namespace: backend
  labels:
    app: tripinsights
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripinsights
  template:
    metadata:
      labels:
        app: tripinsights
    spec:
      containers:
      - name: userprofile
        image: registryhbr8656.azurecr.io/tripinsights/userprofile:latest
        envFrom:
          - secretRef: 
              name: sql-secrets        
        ports:
        - containerPort: 80