apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-deployment
  namespace: backend
  labels:
    deployment: userprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        image: registryhbr8656.azurecr.io/tripinsights/userprofile:latest
        envFrom:
          - secretRef: 
              name: sql-secrets        
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile
  namespace: backend
spec:
  type: ClusterIP
  selector:
    app: userprofile
  ports:
  - port: 80
    protocol: TCP
    name: userprofile-http
  - port: 443
    protocol: TCP
    name: userprofile-https