apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
  namespace: backend
  labels:
    app: poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: ka0923.azurecr.io/poi:v1
        envFrom:
          - secretRef:
               name: sql-secrets
        ports:
        - containerPort: 80