apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-deployment
  namespace: frontend
  labels:
    app: tripviewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: ka0923.azurecr.io/tripviewer:v1
        ports:
        - containerPort: 80