apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-deployment
  namespace: backend
  labels:
    app: userprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        image: ka0923.azurecr.io/userprofile:v1
        ports:
        - containerPort: 80